Fix race condition in Playwright clock pause
`pauseAt` is redundant with `install` and might cause:

> Error: Cannot fast-forward to the past

if we're unlucky.